package rexMiddleware

const (
	RestRbacInterceptorMiddlewareObjectPath       = "path"
	RestRbacInterceptorMiddlewareObjectRequestURI = "requestURI"
)

const (
	CtxSiteDomain      = "SiteDomain"
	CtxStartTime       = "StartTime"
	CtxClientIp        = "ClientIp"
	CtxClientPort      = "ClientPort"
	CtxFullMethod      = "FullMethod"
	CtxRequestURI      = "RequestURI"
	CtxRequestID       = "RequestID"
	CtxTenantId        = "TenantId"
	CtxTenants         = "Tenants"
	CtxDomainId        = "DomainId"
	CtxUserId          = "UserId"
	CtxRole            = "Role"
	CtxClaimsAudience  = "Audience"
	CtxClaimsExpiresAt = "ExpiresAt"
	CtxClaimsId        = "Id"
	CtxClaimsIssuedAt  = "IssuedAt"
	CtxClaimsIssuer    = "Issuer"
	CtxClaimsNotBefore = "NotBefore"
	CtxClaimsSubject   = "Subject"
	CtxUserAgent       = "User-Agent"
	CtxXAccessKeyFor   = "X-AccessKey-For"
	CtxSessionIDFor    = "X-SessionId-For"
	CtxXAuthMethodFor  = "X-AuthMethod-For"
	CtxXAccountFor     = "X-Account-For"
	CtxCityId          = "CityId"
	CtxCountry         = "Country"
	CtxRegion          = "Region"
	CtxProvince        = "Province"
	CtxCity            = "City"
	CtxISP             = "ISP"
	CtxUserAgentFamily = "UserAgent.Family"
	CtxUserAgentMajor  = "UserAgent.Major"
	CtxUserAgentMinor  = "UserAgent.Minor"
	CtxUserAgentPatch  = "UserAgent.Patch"
	CtxOsFamily        = "Os.Family"
	CtxOsMajor         = "Os.Major"
	CtxOsMinor         = "Os.Minor"
	CtxOsPatch         = "Os.Patch"
	CtxOsPatchMinor    = "Os.PatchMinor"
	CtxDeviceFamily    = "Device.Family"
	CtxDeviceBrand     = "Device.Brand"
	CtxDeviceModel     = "Device.Model"
)
