package rexCodes

var WrongMessageEnUS = map[int32]string{
	StatusContinue:                              "Continue",
	StatusSwitchingProtocols:                    "Switching Protocols",
	StatusProcessing:                            "Processing",
	StatusEarlyHints:                            "Early Hints",
	StatusOK:                                    "OK",
	StatusCreated:                               "Created",
	StatusAccepted:                              "Accepted",
	StatusNonAuthoritativeInfo:                  "Non-Authoritative Information",
	StatusNoContent:                             "No Content",
	StatusResetContents:                         "Reset Content",
	StatusPartialContent:                        "Partial Content",
	StatusMultiStatus:                           "Multi-Status",
	StatusAlreadyReported:                       "Already Reported",
	StatusIMUsed:                                "IM Used",
	StatusMultipleChoices:                       "Multiple Choices",
	StatusMovedPermanently:                      "Moved Permanently",
	StatusFound:                                 "Found",
	StatusSeeOther:                              "See Other",
	StatusNotModified:                           "Not Modified",
	StatusUseProxy:                              "Use Proxy",
	Unused:                                      "Unused",
	StatusTemporaryRedirect:                     "Temporary Redirect",
	StatusPermanentRedirect:                     "Permanent Redirect",
	StatusBadRequest:                            "Bad Request",
	StatusUnauthorized:                          "Unauthorized",
	StatusPaymentRequired:                       "Payment Required",
	StatusForbidden:                             "Forbidden",
	StatusNotFound:                              "Not Found",
	StatusMethodNotAllowed:                      "Method Not Allowed",
	StatusNotAcceptable:                         "Not Acceptable",
	StatusProxyAuthRequired:                     "Proxy Authentication Required",
	StatusRequestTimeout:                        "Request Timeout",
	StatusConflict:                              "Conflict",
	StatusGone:                                  "Gone",
	StatusLengthRequired:                        "Length Required",
	StatusPreconditionFailed:                    "Precondition Failed",
	StatusRequestEntityTooLarge:                 "Request Entity Too Large",
	StatusRequestURITooLong:                     "Request URI Too Long",
	StatusUnsupportedMediaType:                  "Unsupported Media Type",
	StatusRequestedRangeNotSatisfiable:          "Requested Range Not Satisfiable",
	StatusExpectationFailed:                     "Expectation Failed",
	StatusTeapot:                                "I'm a teapot",
	StatusMisdirectedRequest:                    "Misdirected Request",
	StatusUnprocessableEntity:                   "Unprocessable Entity",
	StatusLocked:                                "Locked",
	StatusFailedDependency:                      "Failed Dependency",
	StatusTooEarly:                              "Too Early",
	StatusUpgradeRequired:                       "Upgrade Required",
	StatusPreconditionRequired:                  "Precondition Required",
	StatusTooManyRequests:                       "Too Many Requests",
	StatusRequestHeaderFieldsTooLarge:           "Request Header Fields Too Large",
	StatusUnavailableForLegalReasons:            "Unavailable For Legal Reasons",
	StatusInternalServerError:                   "Internal Server Error",
	StatusNotImplemented:                        "Not Implemented",
	StatusBadGateway:                            "Bad Gateway",
	StatusServiceUnavailable:                    "Service Unavailable",
	StatusGatewayTimeout:                        "Gateway Timeout",
	StatusHTTPVersionNotSupported:               "HTTP Version Not Supported",
	StatusVariantAlsoNegotiates:                 "Variant Also Negotiates",
	StatusInsufficientStorage:                   "Insufficient Storage",
	StatusLoopDetected:                          "Loop Detected",
	StatusNotExtended:                           "Not Extended",
	StatusNetworkAuthenticationRequired:         "Network Authentication Required",
	QxEngineStatusContinue:                      "Continue",
	QxEngineStatusSwitchingProtocols:            "Switching Protocols",
	QxEngineStatusProcessing:                    "Processing",
	QxEngineStatusEarlyHints:                    "Early Hints",
	QxEngineStatusAccessTokenInvalid:            "accessToken invalid",
	QxEngineStatusAccessExpired:                 "accessToken expried",
	QxEngineStatusRefreshTokenInvalid:           "refreshToken invalid",
	QxEngineStatusRefreshTokenExpired:           "refreshToken expried",
	QxEngineStatusAccountNotFound:               "account not found",
	QxEngineStatusDisabled:                      "resource is disabled",
	QxEngineStatusNotSetWhiteList:               "not in white list",
	QxEngineStatusNotWhiteList:                  "ip: %s, not in white list",
	QxEngineStatusNotFoundAuthorization:         "not found authorization",
	QxEngineStatusNotFoundXAccessKeyFor:         "not found accesskey",
	QxEngineStatusNotFoundMetadata:              "rpc request not found metadata",
	QxEngineStatusKeyChangeExpired:              "key change expired",
	QxEngineStatusTokenNotActiveYet:             "token not active yet",
	QxEngineStatusSecurityTokenInvalid:          "securityToken Invalid",
	QxEngineStatusSecurityTokenExpired:          "securityToken Expired",
	QxEngineStatusAccountOrPwdInvalid:           "account or password invalid",
	QxEngineStatusSasServiceNotBootstrap:        "sas service not bootstrap",
	QxEngineStatusOK:                            "OK",
	QxEngineStatusCreated:                       "Created",
	QxEngineStatusAccepted:                      "Accepted",
	QxEngineStatusNonAuthoritativeInfo:          "Non-Authoritative Information",
	QxEngineStatusNoContent:                     "No Content",
	QxEngineStatusResetContents:                 "Reset Content",
	QxEngineStatusPartialContent:                "Partial Content",
	QxEngineStatusMultiStatus:                   "Multi-Status",
	QxEngineStatusAlreadyReported:               "Already Reported",
	QxEngineStatusIMUsed:                        "IM Used",
	QxEngineStatusNotTrustDevice:                "not trust device",
	QxEngineStatusAccountExists:                 "account already exists",
	QxEngineStatusResourceExists:                "Resource already exists",
	QxEngineStatusUnsupportedAlgorithmModel:     "Unsupported algorithm model",
	QxEngineStatusUnsupportedSignMethod:         "Unsupported sign method",
	QxEngineStatusMultipleChoices:               "Multiple Choices",
	QxEngineStatusMovedPermanently:              "Moved Permanently",
	QxEngineStatusFound:                         "Found",
	QxEngineStatusSeeOther:                      "See Other",
	QxEngineStatusNotModified:                   "Not Modified",
	QxEngineStatusUseProxy:                      "Use Proxy",
	QxEngineUnused:                              "Unused",
	QxEngineStatusTemporaryRedirect:             "Temporary Redirect",
	QxEngineStatusPermanentRedirect:             "Permanent Redirect",
	QxEngineStatusRedirectSuccess:               "redirect success",
	QxEngineStatusBadRequest:                    "Bad Request",
	QxEngineStatusUnauthorized:                  "Unauthorized",
	QxEngineStatusPaymentRequired:               "Payment Required",
	QxEngineStatusForbidden:                     "Forbidden",
	QxEngineStatusNotFound:                      "Not Found",
	QxEngineStatusMethodNotAllowed:              "Method Not Allowed",
	QxEngineStatusNotAcceptable:                 "Not Acceptable",
	QxEngineStatusProxyAuthRequired:             "Proxy Authentication Required",
	QxEngineStatusRequestTimeout:                "Request Timeout",
	QxEngineStatusConflict:                      "Conflict",
	QxEngineStatusGone:                          "Gone",
	QxEngineStatusLengthRequired:                "Length Required",
	QxEngineStatusPreconditionFailed:            "Precondition Failed",
	QxEngineStatusRequestEntityTooLarge:         "Request Entity Too Large",
	QxEngineStatusRequestURITooLong:             "Request URI Too Long",
	QxEngineStatusUnsupportedMediaType:          "Unsupported Media Type",
	QxEngineStatusRequestedRangeNotSatisfiable:  "Requested Range Not Satisfiable",
	QxEngineStatusExpectationFailed:             "Expectation Failed",
	QxEngineStatusTeapot:                        "I'm a teapot",
	QxEngineStatusMisdirectedRequest:            "Misdirected Request",
	QxEngineStatusUnprocessableEntity:           "Unprocessable Entity",
	QxEngineStatusLocked:                        "Locked",
	QxEngineStatusFailedDependency:              "Failed Dependency",
	QxEngineStatusTooEarly:                      "Too Early",
	QxEngineStatusUpgradeRequired:               "Upgrade Required",
	QxEngineStatusPreconditionRequired:          "Precondition Required",
	QxEngineStatusTooManyRequests:               "Too Many Requests",
	QxEngineStatusRequestHeaderFieldsTooLarge:   "Request Header Fields Too Large",
	QxEngineStatusUnavailableForLegalReasons:    "Unavailable For Legal Reasons",
	QxEngineStatusAccountOrPasswordInvalid:      "account or password invalid",
	QxEngineStatusPermissionDenied:              "permission denied",
	QxEngineStatusNotStandardBase64Format:       "Not in standard base64 format",
	QxEngineStatusKmsNotInit:                    "The tenants kms has not yet been initialized",
	QxEngineStatusFunctionUnavailable:           "Function Unavailable",
	QxEngineStatusCodeInvalid:                   "Code Invalid",
	QxEngineStatusInternalServerError:           "Internal Server Error",
	QxEngineStatusNotImplemented:                "Not Implemented",
	QxEngineStatusBadGateway:                    "Bad Gateway",
	QxEngineStatusServiceUnavailable:            "Service Unavailable",
	QxEngineStatusGatewayTimeout:                "Gateway Timeout",
	QxEngineStatusHTTPVersionNotSupported:       "HTTP Version Not Supported",
	QxEngineStatusVariantAlsoNegotiates:         "Variant Also Negotiates",
	QxEngineStatusInsufficientStorage:           "Insufficient Storage",
	QxEngineStatusLoopDetected:                  "Loop Detected",
	QxEngineStatusNotExtended:                   "Not Extended",
	QxEngineStatusNetworkAuthenticationRequired: "Network Authentication Required",
	QxEngineStatusParserInitFailed:              "Parser Init Failed",
	QxEngineStatusServerEcdhUnSupported:         "ecdh not supported",
	BsStatusContinue:                            "Continue",
	BsStatusSwitchingProtocols:                  "Switching Protocols",
	BsStatusProcessing:                          "Processing",
	BsStatusEarlyHints:                          "Early Hints",
	BsStatusAccountNotFound:                     "account not found",
	BsStatusAccountOrPwdInvalid:                 "account or password invalid",
	BsStatusOK:                                  "OK",
	BsStatusCreated:                             "Created",
	BsStatusAccepted:                            "Accepted",
	BsStatusNonAuthoritativeInfo:                "Non-Authoritative Information",
	BsStatusNoContent:                           "No Content",
	BsStatusResetContents:                       "Reset Content",
	BsStatusPartialContent:                      "Partial Content",
	BsStatusMultiStatus:                         "Multi-Status",
	BsStatusAlreadyReported:                     "Already Reported",
	BsStatusIMUsed:                              "IM Used",
	OauthAcrRequiredLevel:                       "Acr required level does not meet the standard",
	OauthMultipleAccount:                        "This phone number has multiple bound accounts",
	BsStatusResourceExists:                      "Resource already exists",
	BsStatusMultipleChoices:                     "Multiple Choices",
	BsStatusMovedPermanently:                    "Moved Permanently",
	BsStatusFound:                               "Found",
	BsStatusSeeOther:                            "See Other",
	BsStatusNotModified:                         "Not Modified",
	BsStatusUseProxy:                            "Use Proxy",
	BsUnused:                                    "Unused",
	BsStatusTemporaryRedirect:                   "Temporary Redirect",
	BsStatusPermanentRedirect:                   "Permanent Redirect",
	BsStatusBadRequest:                          "Bad Request",
	BsStatusUnauthorized:                        "Unauthorized",
	BsStatusPaymentRequired:                     "Payment Required",
	BsStatusForbidden:                           "Forbidden",
	BsStatusNotFound:                            "Not Found",
	BsStatusMethodNotAllowed:                    "Method Not Allowed",
	BsStatusNotAcceptable:                       "Not Acceptable",
	BsStatusProxyAuthRequired:                   "Proxy Authentication Required",
	BsStatusRequestTimeout:                      "Request Timeout",
	BsStatusConflict:                            "Conflict",
	BsStatusGone:                                "Gone",
	BsStatusLengthRequired:                      "Length Required",
	BsStatusPreconditionFailed:                  "Precondition Failed",
	BsStatusRequestEntityTooLarge:               "Request Entity Too Large",
	BsStatusRequestURITooLong:                   "Request URI Too Long",
	BsStatusUnsupportedMediaType:                "Unsupported Media Type",
	BsStatusRequestedRangeNotSatisfiable:        "Requested Range Not Satisfiable",
	BsStatusExpectationFailed:                   "Expectation Failed",
	BsStatusTeapot:                              "I'm a teapot",
	BsStatusMisdirectedRequest:                  "Misdirected Request",
	BsStatusUnprocessableEntity:                 "Unprocessable Entity",
	BsStatusLocked:                              "Locked",
	BsStatusFailedDependency:                    "Failed Dependency",
	BsStatusTooEarly:                            "Too Early",
	BsStatusUpgradeRequired:                     "Upgrade Required",
	BsStatusPreconditionRequired:                "Precondition Required",
	BsStatusTooManyRequests:                     "Too Many Requests",
	BsStatusRequestHeaderFieldsTooLarge:         "Request Header Fields Too Large",
	BsStatusUnavailableForLegalReasons:          "Unavailable For Legal Reasons",
	BsStatusOauth2UnsupportedResponseType:       "unsupported response_type",
	BsStatusOauth2InvalidClient:                 "invalid client",
	BsStatusOauth2InvalidRedirectUri:            "invalid redirect_uri",
	BsStatusOauth2InvalidScope:                  "invalid scope",
	BsStatusOauth2InvalidState:                  "invalid state",
	BsStatusOauth2InvalidNonce:                  "invalid nonce",
	BsStatusOauth2UnsupportedGrantType:          "unsupported grant_type",
	BsStatusOauth2CodeExpired:                   "oauth2: code expired",
	BsStatusOauth2CodeRevoked:                   "oauth2: code revoked",
	BsStatusOauth2CodeUsed:                      "oauth2: code used",
	BsStatusOauth2ClientIdNotMatch:              "client_id not match",
	BsStatusOauth2RedirectUriNotMatch:           "redirect_uri not match",
	BsStatusOauth2CodeVerifierIsEmpty:           "code_verifier is empty",
	BsStatusOauth2CodeVerifierNotMatch:          "code_verifier not match",
	BsStatusOauth2ClientSecretIsEmpty:           "client_secret is empty",
	BsStatusOauth2ClientSecretNotMatch:          "client_secret not match",
	BsStatusOauth2ClientIdDisabled:              "client_id is disabled",
	BsStatusCodeInvalid:                         "Code Invalid",
	BsStatusPermissionDenied:                    "permission denied",
	BsStatusRefreshTokenExpired:                 "refresh_token expired",
	BsStatusInternalServerError:                 "Internal Server Error",
	BsStatusNotImplemented:                      "Not Implemented",
	BsStatusBadGateway:                          "Bad Gateway",
	BsStatusServiceUnavailable:                  "Service Unavailable",
	BsStatusGatewayTimeout:                      "Gateway Timeout",
	BsStatusHTTPVersionNotSupported:             "HTTP Version Not Supported",
	BsStatusVariantAlsoNegotiates:               "Variant Also Negotiates",
	BsStatusInsufficientStorage:                 "Insufficient Storage",
	BsStatusLoopDetected:                        "Loop Detected",
	BsStatusNotExtended:                         "Not Extended",
	BsStatusNetworkAuthenticationRequired:       "Network Authentication Required",
}
