package rexCodes

var WrongMessageEnUS = map[int32]string{
	FAIL:                                      "FAIL",
	OK:                                        "OK",
	StatusContinue:                            "Continue",
	StatusSwitchingProtocols:                  "Switching Protocols",
	StatusProcessing:                          "Processing",
	StatusEarlyHints:                          "Early Hints",
	StatusOK:                                  "OK",
	StatusCreated:                             "Created",
	StatusAccepted:                            "Accepted",
	StatusNonAuthoritativeInfo:                "Non-Authoritative Information",
	StatusNoContent:                           "No Content",
	StatusResetContents:                       "Reset Content",
	StatusPartialContent:                      "Partial Content",
	StatusMultiStatus:                         "Multi-Status",
	StatusAlreadyReported:                     "Already Reported",
	StatusIMUsed:                              "IM Used",
	StatusMultipleChoices:                     "Multiple Choices",
	StatusMovedPermanently:                    "Moved Permanently",
	StatusFound:                               "Found",
	StatusSeeOther:                            "See Other",
	StatusNotModified:                         "Not Modified",
	StatusUseProxy:                            "Use Proxy",
	Unused:                                    "Unused",
	StatusTemporaryRedirect:                   "Temporary Redirect",
	StatusPermanentRedirect:                   "Permanent Redirect",
	StatusBadRequest:                          "Bad Request",
	StatusUnauthorized:                        "Unauthorized",
	StatusPaymentRequired:                     "Payment Required",
	StatusForbidden:                           "Forbidden",
	StatusNotFound:                            "Not Found",
	StatusMethodNotAllowed:                    "Method Not Allowed",
	StatusNotAcceptable:                       "Not Acceptable",
	StatusProxyAuthRequired:                   "Proxy Authentication Required",
	StatusRequestTimeout:                      "Request Timeout",
	StatusConflict:                            "Conflict",
	StatusGone:                                "Gone",
	StatusLengthRequired:                      "Length Required",
	StatusPreconditionFailed:                  "Precondition Failed",
	StatusRequestEntityTooLarge:               "Request Entity Too Large",
	StatusRequestURITooLong:                   "Request URI Too Long",
	StatusUnsupportedMediaType:                "Unsupported Media Type",
	StatusRequestedRangeNotSatisfiable:        "Requested Range Not Satisfiable",
	StatusExpectationFailed:                   "Expectation Failed",
	StatusTeapot:                              "I'm a teapot",
	StatusMisdirectedRequest:                  "Misdirected Request",
	StatusUnprocessableEntity:                 "Unprocessable Entity",
	StatusLocked:                              "Locked",
	StatusFailedDependency:                    "Failed Dependency",
	StatusTooEarly:                            "Too Early",
	StatusUpgradeRequired:                     "Upgrade Required",
	StatusPreconditionRequired:                "Precondition Required",
	StatusTooManyRequests:                     "Too Many Requests",
	StatusRequestHeaderFieldsTooLarge:         "Request Header Fields Too Large",
	StatusUnavailableForLegalReasons:          "Unavailable For Legal Reasons",
	StatusInternalServerError:                 "Internal Server Error",
	StatusNotImplemented:                      "Not Implemented",
	StatusBadGateway:                          "Bad Gateway",
	StatusServiceUnavailable:                  "Service Unavailable",
	StatusGatewayTimeout:                      "Gateway Timeout",
	StatusHTTPVersionNotSupported:             "HTTP Version Not Supported",
	StatusVariantAlsoNegotiates:               "Variant Also Negotiates",
	StatusInsufficientStorage:                 "Insufficient Storage",
	StatusLoopDetected:                        "Loop Detected",
	StatusNotExtended:                         "Not Extended",
	StatusNetworkAuthenticationRequired:       "Network Authentication Required",
	EngineStatusContinue:                      "Continue",
	EngineStatusSwitchingProtocols:            "Switching Protocols",
	EngineStatusProcessing:                    "Processing",
	EngineStatusEarlyHints:                    "Early Hints",
	EngineStatusAccessTokenInvalid:            "accessToken invalid",
	EngineStatusAccessExpired:                 "accessToken expried",
	EngineStatusRefreshTokenInvalid:           "refreshToken invalid",
	EngineStatusRefreshTokenExpired:           "refreshToken expried",
	EngineStatusAccountNotFound:               "account not found",
	EngineStatusDisabled:                      "resource is disabled",
	EngineStatusNotSetWhiteList:               "not in white list",
	EngineStatusNotWhiteList:                  "ip: %s, not in white list",
	EngineStatusNotFoundAuthorization:         "not found authorization",
	EngineStatusNotFoundXAccessKeyFor:         "not found accesskey",
	EngineStatusNotFoundMetadata:              "rpc request not found metadata",
	EngineStatusKeyChangeExpired:              "key change expired",
	EngineStatusTokenNotActiveYet:             "token not active yet",
	EngineStatusSecurityTokenInvalid:          "securityToken Invalid",
	EngineStatusSecurityTokenExpired:          "securityToken Expired",
	EngineStatusAccountOrPwdInvalid:           "account or password invalid",
	EngineStatusSasServiceNotBootstrap:        "sas service not bootstrap",
	EngineStatusOK:                            "OK",
	EngineStatusCreated:                       "Created",
	EngineStatusAccepted:                      "Accepted",
	EngineStatusNonAuthoritativeInfo:          "Non-Authoritative Information",
	EngineStatusNoContent:                     "No Content",
	EngineStatusResetContents:                 "Reset Content",
	EngineStatusPartialContent:                "Partial Content",
	EngineStatusMultiStatus:                   "Multi-Status",
	EngineStatusAlreadyReported:               "Already Reported",
	EngineStatusIMUsed:                        "IM Used",
	EngineStatusNotTrustDevice:                "not trust device",
	EngineStatusAccountExists:                 "account already exists",
	EngineStatusResourceExists:                "Resource already exists",
	EngineStatusUnsupportedAlgorithmModel:     "Unsupported algorithm model",
	EngineStatusUnsupportedSignMethod:         "Unsupported sign method",
	EngineStatusMultipleChoices:               "Multiple Choices",
	EngineStatusMovedPermanently:              "Moved Permanently",
	EngineStatusFound:                         "Found",
	EngineStatusSeeOther:                      "See Other",
	EngineStatusNotModified:                   "Not Modified",
	EngineStatusUseProxy:                      "Use Proxy",
	EngineUnused:                              "Unused",
	EngineStatusTemporaryRedirect:             "Temporary Redirect",
	EngineStatusPermanentRedirect:             "Permanent Redirect",
	EngineStatusRedirectSuccess:               "redirect success",
	EngineStatusBadRequest:                    "Bad Request",
	EngineStatusUnauthorized:                  "Unauthorized",
	EngineStatusPaymentRequired:               "Payment Required",
	EngineStatusForbidden:                     "Forbidden",
	EngineStatusNotFound:                      "Not Found",
	EngineStatusMethodNotAllowed:              "Method Not Allowed",
	EngineStatusNotAcceptable:                 "Not Acceptable",
	EngineStatusProxyAuthRequired:             "Proxy Authentication Required",
	EngineStatusRequestTimeout:                "Request Timeout",
	EngineStatusConflict:                      "Conflict",
	EngineStatusGone:                          "Gone",
	EngineStatusLengthRequired:                "Length Required",
	EngineStatusPreconditionFailed:            "Precondition Failed",
	EngineStatusRequestEntityTooLarge:         "Request Entity Too Large",
	EngineStatusRequestURITooLong:             "Request URI Too Long",
	EngineStatusUnsupportedMediaType:          "Unsupported Media Type",
	EngineStatusRequestedRangeNotSatisfiable:  "Requested Range Not Satisfiable",
	EngineStatusExpectationFailed:             "Expectation Failed",
	EngineStatusTeapot:                        "I'm a teapot",
	EngineStatusMisdirectedRequest:            "Misdirected Request",
	EngineStatusUnprocessableEntity:           "Unprocessable Entity",
	EngineStatusLocked:                        "Locked",
	EngineStatusFailedDependency:              "Failed Dependency",
	EngineStatusTooEarly:                      "Too Early",
	EngineStatusUpgradeRequired:               "Upgrade Required",
	EngineStatusPreconditionRequired:          "Precondition Required",
	EngineStatusTooManyRequests:               "Too Many Requests",
	EngineStatusRequestHeaderFieldsTooLarge:   "Request Header Fields Too Large",
	EngineStatusUnavailableForLegalReasons:    "Unavailable For Legal Reasons",
	EngineStatusAccountOrPasswordInvalid:      "account or password invalid",
	EngineStatusPermissionDenied:              "permission denied",
	EngineStatusNotStandardBase64Format:       "Not in standard base64 format",
	EngineStatusKmsNotInit:                    "The tenants kms has not yet been initialized",
	EngineStatusFunctionUnavailable:           "Function Unavailable",
	EngineStatusCodeInvalid:                   "Code Invalid",
	EngineStatusInternalServerError:           "Internal Server Error",
	EngineStatusNotImplemented:                "Not Implemented",
	EngineStatusBadGateway:                    "Bad Gateway",
	EngineStatusServiceUnavailable:            "Service Unavailable",
	EngineStatusGatewayTimeout:                "Gateway Timeout",
	EngineStatusHTTPVersionNotSupported:       "HTTP Version Not Supported",
	EngineStatusVariantAlsoNegotiates:         "Variant Also Negotiates",
	EngineStatusInsufficientStorage:           "Insufficient Storage",
	EngineStatusLoopDetected:                  "Loop Detected",
	EngineStatusNotExtended:                   "Not Extended",
	EngineStatusNetworkAuthenticationRequired: "Network Authentication Required",
	EngineStatusParserInitFailed:              "Parser Init Failed",
	EngineStatusServerEcdhUnSupported:         "ecdh not supported",
	BsStatusContinue:                          "Continue",
	BsStatusSwitchingProtocols:                "Switching Protocols",
	BsStatusProcessing:                        "Processing",
	BsStatusEarlyHints:                        "Early Hints",
	BsStatusAccountNotFound:                   "account not found",
	BsStatusNotFoundMetadata:                  "not found metadata",
	BsStatusAccountOrPwdInvalid:               "account or password invalid",
	BsStatusOK:                                "OK",
	BsStatusCreated:                           "Created",
	BsStatusAccepted:                          "Accepted",
	BsStatusNonAuthoritativeInfo:              "Non-Authoritative Information",
	BsStatusNoContent:                         "No Content",
	BsStatusResetContents:                     "Reset Content",
	BsStatusPartialContent:                    "Partial Content",
	BsStatusMultiStatus:                       "Multi-Status",
	BsStatusAlreadyReported:                   "Already Reported",
	BsStatusIMUsed:                            "IM Used",
	OauthAcrRequiredLevel:                     "Acr required level does not meet the standard",
	OauthMultipleAccount:                      "This phone number has multiple bound accounts",
	BsStatusResourceExists:                    "Resource already exists",
	BsStatusMultipleChoices:                   "Multiple Choices",
	BsStatusMovedPermanently:                  "Moved Permanently",
	BsStatusFound:                             "Found",
	BsStatusSeeOther:                          "See Other",
	BsStatusNotModified:                       "Not Modified",
	BsStatusUseProxy:                          "Use Proxy",
	BsUnused:                                  "Unused",
	BsStatusTemporaryRedirect:                 "Temporary Redirect",
	BsStatusPermanentRedirect:                 "Permanent Redirect",
	BsStatusBadRequest:                        "Bad Request",
	BsStatusUnauthorized:                      "Unauthorized",
	BsStatusPaymentRequired:                   "Payment Required",
	BsStatusForbidden:                         "Forbidden",
	BsStatusNotFound:                          "Not Found",
	BsStatusMethodNotAllowed:                  "Method Not Allowed",
	BsStatusNotAcceptable:                     "Not Acceptable",
	BsStatusProxyAuthRequired:                 "Proxy Authentication Required",
	BsStatusRequestTimeout:                    "Request Timeout",
	BsStatusConflict:                          "Conflict",
	BsStatusGone:                              "Gone",
	BsStatusLengthRequired:                    "Length Required",
	BsStatusPreconditionFailed:                "Precondition Failed",
	BsStatusRequestEntityTooLarge:             "Request Entity Too Large",
	BsStatusRequestURITooLong:                 "Request URI Too Long",
	BsStatusUnsupportedMediaType:              "Unsupported Media Type",
	BsStatusRequestedRangeNotSatisfiable:      "Requested Range Not Satisfiable",
	BsStatusExpectationFailed:                 "Expectation Failed",
	BsStatusTeapot:                            "I'm a teapot",
	BsStatusMisdirectedRequest:                "Misdirected Request",
	BsStatusUnprocessableEntity:               "Unprocessable Entity",
	BsStatusLocked:                            "Locked",
	BsStatusFailedDependency:                  "Failed Dependency",
	BsStatusTooEarly:                          "Too Early",
	BsStatusUpgradeRequired:                   "Upgrade Required",
	BsStatusPreconditionRequired:              "Precondition Required",
	BsStatusTooManyRequests:                   "Too Many Requests",
	BsStatusRequestHeaderFieldsTooLarge:       "Request Header Fields Too Large",
	BsStatusUnavailableForLegalReasons:        "Unavailable For Legal Reasons",
	BsStatusOauth2UnsupportedResponseType:     "unsupported response_type",
	BsStatusOauth2InvalidClient:               "invalid client",
	BsStatusOauth2InvalidRedirectUri:          "invalid redirect_uri",
	BsStatusOauth2InvalidScope:                "invalid scope",
	BsStatusOauth2InvalidState:                "invalid state",
	BsStatusOauth2InvalidNonce:                "invalid nonce",
	BsStatusOauth2UnsupportedGrantType:        "unsupported grant_type",
	BsStatusOauth2CodeExpired:                 "oauth2: code expired",
	BsStatusOauth2CodeRevoked:                 "oauth2: code revoked",
	BsStatusOauth2CodeUsed:                    "oauth2: code used",
	BsStatusOauth2ClientIdNotMatch:            "client_id not match",
	BsStatusOauth2RedirectUriNotMatch:         "redirect_uri not match",
	BsStatusOauth2CodeVerifierIsEmpty:         "code_verifier is empty",
	BsStatusOauth2CodeVerifierNotMatch:        "code_verifier not match",
	BsStatusOauth2ClientSecretIsEmpty:         "client_secret is empty",
	BsStatusOauth2ClientSecretNotMatch:        "client_secret not match",
	BsStatusOauth2ClientIdDisabled:            "client_id is disabled",
	BsStatusCodeInvalid:                       "Code Invalid",
	BsStatusPermissionDenied:                  "permission denied",
	BsStatusRefreshTokenExpired:               "refresh_token expired",
	BsStatusNeedUpdateBrowserVersion:          "Please update your browser version",
	BsStatusIdpNotAllowDirectLogin:            "Idp does not allow direct login",
	BsStatusOauth2LoginNotCompleted:           "The login process has not been completed",
	BsStatusInternalServerError:               "Internal Server Error",
	BsStatusNotImplemented:                    "Not Implemented",
	BsStatusBadGateway:                        "Bad Gateway",
	BsStatusServiceUnavailable:                "Service Unavailable",
	BsStatusGatewayTimeout:                    "Gateway Timeout",
	BsStatusHTTPVersionNotSupported:           "HTTP Version Not Supported",
	BsStatusVariantAlsoNegotiates:             "Variant Also Negotiates",
	BsStatusInsufficientStorage:               "Insufficient Storage",
	BsStatusLoopDetected:                      "Loop Detected",
	BsStatusNotExtended:                       "Not Extended",
	BsStatusNetworkAuthenticationRequired:     "Network Authentication Required",
}
